"""Create user quote and template models

Revision ID: cf32a933aa03
Revises: 
Create Date: 2026-04-06 16:20:06.326648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf32a933aa03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('follow_up_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_template_user_id'), ['user_id'], unique=False)

    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('quote_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_method', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('last_followed_up_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_next_follow_up_date'), ['next_follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_user_id'))
        batch_op.drop_index(batch_op.f('ix_quote_status'))
        batch_op.drop_index(batch_op.f('ix_quote_next_follow_up_date'))

    op.drop_table('quote')
    with op.batch_alter_table('follow_up_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_template_user_id'))

    op.drop_table('follow_up_template')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
